name: Build Multibranch
on:
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        description: Build profile to use
        options:
          - development
          - preview
          - production
      environment:
        type: choice
        description: Environment to deploy to
        options:
          - main
          - qa
          - stg
jobs:
  build-and-test:
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: "android"
            os: "ubuntu-latest"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.environment }}

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm install

      - name: Crear archivo .env
        env:
          EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY }}
        run: |
          echo "EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY=${EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY}" >> .env

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Setup Java SDK
        if: ${{ matrix.platform == 'android' }}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Get package version
        id: get-version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build
        run: |
          eas build --local \
            --non-interactive \
            --output=./aira-native-${{ env.VERSION }}.apk \
            --platform=${{ matrix.platform }} \
            --profile=${{ github.event.inputs.profile }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: aira-native-${{ matrix.platform }}-${{ env.VERSION }}
          path: aira-native-${{ env.VERSION }}.apk
